[package]
name = "onitama-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug = true
lto = true
codegen-units = 1

[dependencies]
seq-macro = "0.3.1"
bit-iter = "1.1.1"
rayon = "1.7.0"
